# run on container-based infrastructure
sudo: false

language: python

matrix:
    include:
    - python: 3.6
    - python: 3.7
      sudo: required
      dist: xenial

install:
    - pip install flake8

script:
    # test PEP8 compliance
    - flake8 --max-line-length=80 --extend-ignore=E731 .
